FROM golang:1.24-alpine AS base

WORKDIR /app

RUN apk add --no-cache build-base

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

CMD ["air", "-c", "air.toml"]
